# [VIEW]
# The prefix that will be added to the message
ad-prefix: "***** "

# The postfix that will be added to the message
ad-postfix: " *****"

# Player signature format. It will right before the postfix.
# Make it an empty string if not needed.
ad-player-signature-format: " (%s)"

# If true, then if there are "\n" symbols inside the message,
# as well as prefix, postfix and signature,
# the message will be divided into different lines by these symbols
ad-use-multi-line: true

# [LOGIC]
# Sets the time threshold at which players can write ad messages.
# Specified in seconds.
ad-threshold-per-player: 1800

# The flag indicates whether the user's timestamps should be saved immediately.
# Default is false, timestamps are stored in runtime, and
# they are saved to a file when the plugin or server is turned off.
ad-threshold-save-file-immediately: false

# Maximum message length from the user (without prefix, postfix and suffix).
# If equal to the negative number (e.g. -1), then there are no size restrictions.
ad-max-message-length: 255

# Minimum message length from the user (without prefix, postfix and suffix).
# If equal to the negative number (e.g. -1), then there are no size restrictions.
ad-min-message-length: 25

# Specifies whether prefixes and suffixes from LuckPerms should be used in player's signature
ad-use-luck-perms-placeholders: true

# [MESSAGES]
resources:
  command-only-for-players: "&cГэтая каманда толькі для гульцоў"
  wait-to-use-command: "&cВы нядаўна ўжо карысталіся гэтай камандай. Пачакайце яшчэ %s."
  message-too-large: "&cПаведамленне занадта вялікае. Максімальны памер паведамлення: %d знакаў."
  message-too-small: "&cПаведамленне занадта маленькае. Мінімальны памер паведамлення: %d знакаў."