# ads display settings
ad-prefix: "***** "
ad-postfix: " *****"

# sets the time threshold at which players can write ad messages
# specified in seconds
ad-threshold-per-player: 1800
ad-threshold-save-file-immediately: false

# localizable resources
resources:
  command-only-for-players: "Гэтая каманда толькі для гульцоў"
  wait-to-use-command: "Вы нядаўна ўжо карысталіся гэтай камандай. Пачакайце яшчэ %s."